Allow to define custom differ object in matchers
rspec/rspec-expectations pull request #1096
Opened 2019-01-16 21:02 UTC by sponomarev

The questions about custom differ already appeared in the past in #627, #97. I think it could be valuable to allow custom differ objects in matchers.

The proposed solution should be completely backward compatible. And, I hope, will provide a way to extend custom RSpec matchers libraries.

2019-01-16 21:48 UTC, JonRowe requested changes
As this stands this changes a public API so cannot be merged at this point. I'm also not sure having a matcher level differ makes any sense, we're interested in building a new built in differ for RSpec 4, and I'm open to providing configurable differs globally, but per matcher has problems.

2019-01-16 21:48 UTC, JonRowe commented on lib/rspec/expectations/fail_with.rb
> +      def fail_with(message, matcher=nil)
I'm afraid you can't do this, it changes a public api.

2019-01-16 21:48 UTC, JonRowe commented on spec/rspec/expectations/fail_with_spec.rb
> +    actual = "foo bar baz\n"
To prove your new implementation works, these should have been left alone.

2019-01-16 21:49 UTC, JonRowe commented on lib/rspec/expectations/fail_with.rb
> +        message = if !matcher.nil?
As you can see above we already inject the differ, it just can't come from a param here, or at least, it'd have to be an extra param.

2019-01-16 21:51 UTC, JonRowe commented on lib/rspec/expectations/fail_with.rb
> +                    ::RSpec::Matchers::ExpectedsForMultipleDiffs.from(nil).message_with_diff(message, differ, nil)
I'm yeah nahing this, expected and actual need to be passed in, differ could be an optional extra, this would eliminate the need for this if.

2019-01-16 21:51 UTC, JonRowe commented on spec/rspec/expectations/fail_with_spec.rb
> +      |+["poo", "car"]
To be backwards compatible, existing specs shouldn't change...

2020-01-11 15:59 UTC, pirj commented
Would you be interested in taking another approach to the problem @sponomarev ?

2020-01-14 21:02 UTC, benoittgt commented
I am interested to work on this if @sponomarev can not, after I finish the task on documentation and yard. https://github.com/rspec/rspec-dev/pull/233

2020-01-15 07:49 UTC, sponomarev commented
@pirj Yeah, for sure. I'll take care of it this week. @benoittgt thanks for the offer, I think I'll deal with it on my own =)

2020-06-11 08:09 UTC, pirj commented
@sponomarev A friendly reminder

2020-09-25 22:07 UTC, benoittgt commented
@sponomarev Little bump on this one 😊

2024-11-30 11:28 UTC, JonRowe commented
I'm closing this as part of the monorepo migration, we are interested in a pluggable differ overall but this isn't the right approach.

2024-11-30 11:28 UTC, closed without merging