Present the actual error message from raise_error
rspec/rspec-expectations pull request #1330
Opened 2021-10-27 04:14 UTC by genehsu

Fixes #1190 

Display the actual error message of the raised error when a raise_error
assertion fails.  The failure message will now include the error message
on a separate line followed by the backtrace.  If there is no error
message, only the backtrace will be shown.

If this approach is not correct, then please close this PR without prejudice 😃

2021-11-03 03:30 UTC, JonRowe commented on lib/rspec/matchers/built_in/raise_error.rb
> +          ].flatten.join('')
This array could probably just be interpolation now, as the intent of the original map is taken care of by the zip.

2021-11-03 03:32 UTC, JonRowe requested changes
Thanks for tackling this, can you check out these couple of suggestions?

2021-11-03 03:32 UTC, JonRowe commented on spec/rspec/matchers/built_in/raise_error_spec.rb
> +    s = StandardError.new("Error 1")
Rather than `s` can you use a proper name like `error`

2021-11-03 03:32 UTC, JonRowe commented on lib/rspec/matchers/built_in/raise_error.rb
> +            message_text = [" with message:", *message_lines].zip(["\n  # "] * message_lines.size)
given that the magic string `"\n  # "` is now used multiple times it might be best to assign it and reuse it

2021-11-03 17:42 UTC, genehsu commented
@JonRowe 
> Thanks for tackling this, can you check out these couple of suggestions?

Thanks for the review. I believe I've addressed your suggestions with clearer code. Let me know if you have any other suggestions to the code or output.

2024-11-30 12:13 UTC, JonRowe commented
Migrated to the monorepo as rspec/rspec#128

2024-11-30 12:13 UTC, closed without merging