Update matchers to show detected string encoding differences
rspec/rspec-expectations pull request #1425
Opened 2023-06-29 13:53 UTC by AlanFoster

closes https://github.com/rspec/rspec-expectations/issues/1422

Updates the `eq` and `eql` matchers to show detected string encoding differences - https://github.com/rspec/rspec-expectations/issues/1422

### Before

Unclear why the test is failing. For an average user this might be confusing:

```
Example F

  1) Example Example
     Failure/Error: expect(actual).to eq(expected)

       expected: "abc"
            got: "abc"

       (compared using ==)
```

### After

Immediately clear that the string encodings are not the same and the tests might be impacted by this difference:

```
Example F

  1) Example Example
     Failure/Error: expect(actual).to eq(expected)

       expected: #<Encoding:ASCII-8BIT> "abc"
            got: #<Encoding:UTF-16LE> "abc"

       (compared using ==)
```

2023-07-05 23:42 UTC, AlanFoster commented
> 1 workflow awaiting approval
> This workflow requires approval from a maintainer.

@pirj Sorry for the ping, CI approval would be appreciated 🎉

2023-07-06 07:27 UTC, JonRowe requested changes
Stylistically we prefer to conditonally define methods rather than do runtime checks for old rubies, makes it easier to remove the backports when the time comes. We do a lot of similar work on encoded string in rspec-support

2023-07-06 07:27 UTC, JonRowe commented on lib/rspec/matchers/built_in/base_matcher.rb
> +          end
We prefer to conditionally define things like this:
```suggestion
          if String.method_defined?(:encoding)
            def string_encoding_differs?
              actual.is_a?(String) && expected.is_a?(String) && actual.encoding != expected.encoding
            end
          else
            def string_encoding_differs?
              false
            end
          end
```

2023-07-06 07:27 UTC, JonRowe commented on lib/rspec/matchers/built_in/base_matcher.rb
> +          end
This should also be conditionally defined to protect against accidental usage

2023-07-11 22:11 UTC, merged

2023-07-11 22:13 UTC, JonRowe commented
Thanks 🙏

2024-02-04 13:06 UTC, JonRowe commented
Released in 3.13.0 apologies for the delay.