Add configuration for max object formatter length
rspec/rspec-expectations pull request #951
Opened 2016-11-03 15:31 UTC by samphippen

2016-11-03 15:32 UTC, samphippen commented
Fixes: https://github.com/rspec/rspec-support/issues/252#issuecomment-257839067

r? @rspec/rspec

2016-11-03 16:21 UTC, xaviershay commented
kinda makes me sad that we need to extend configuration API further but LGTM pending green build

2016-11-03 21:10 UTC, liam-m requested changes

2016-11-05 14:57 UTC, samphippen commented
r? @JonRowe

2016-11-05 23:15 UTC, JonRowe requested changes

2016-11-05 23:15 UTC, JonRowe commented on spec/rspec/expectations/configuration_spec.rb
> +          config.max_formatted_output_length = 10
This needs to be restored after it's changed, or otherwise isolated, as it's currently leaking and breaking the build :(

2018-04-25 07:11 UTC, benoittgt commented
I'm interested to work on this. So we need to make this setting only available for a `context`, `describe`, `it` block? 

Does it means that every time a test run we should check after that `max_formatted_output_length` is not different from a default value. If it's different we change it to default?

Looks like a hack for me. 😟

Maybe I could work instead on displaying differences like mentioned here https://github.com/rspec/rspec-core/issues/2535#issue-312110983 even if this look quick hard to implement at first sight.

2018-04-25 08:49 UTC, JonRowe commented
@benoittgt no the setting is fine, its the test, the test needs to ensure that the config is restored to its original state afterwards

2018-04-25 09:49 UTC, benoittgt commented
Oh ok thanks @JonRowe. Will make a PR for that if it's ok.

2018-04-25 09:50 UTC, JonRowe commented
👍

2018-04-25 10:10 UTC, benoittgt commented
See https://github.com/rspec/rspec-expectations/pull/1056 for potential test fix.

2018-04-25 15:13 UTC, closed without merging